config/routes.rb
Rails.application.routes.draw do
  get 'pages/landing'
  root 'pages#landing'


  resources :homes do
    member do
      post 'favorite'
      post 'unfavorite'
    end
  end

  get '/search' => 'homes#index'

  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  '/login'  => 'session#new'
  post '/login'  => 'session#create'
  get  '/logout' => 'session#destroy'

  # mount Shrine::DownloadEndpoint => "/attachments"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :home
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
  include ImageUploader[:image]

  belongs_to :created_by, class_name: "User"

  def can_this_user_edit?(user)
    return created_by == user
  end

  def can_this_user_destroy?(user)
    return created_by == user
  end

  def self.search(search)
    where("address ILIKE ? or city ILIKE ? or state ILIKE ? or zip ILIKE ? or description ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" , "%#{search}%")
  end
end

app/models/image_uploader.rb
require "image_processing/mini_magick"

class ImageUploader < Shrine
  # plugins and uploading logic
  include ImageUploader[:image]

  include ImageProcessing::MiniMagick
    plugin :processing
    plugin :versions   # enable Shrine to handle a hash of files
    plugin :delete_raw # delete processed files after uploading

    process(:store) do |io, context|
      original = io.download

      size_800 = resize_to_limit!(original, 800, 800) { |cmd| cmd.auto_orient } # orient rotated images
      size_500 = resize_to_limit(size_800,  450, 450)
      size_300 = resize_to_limit(size_500,  300, 300)
      size_64  = resize_to_limit(size_300, 64, 64)

      {original: io, large: size_800, medium: size_500, small: size_300, thumbnail: size_64}
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Factory method to create a user from some omniauth data
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Assign the current user
  def current_user=(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in filter to ensure the user is logged in
  def authenticate!
    unless logged_in?
      # redirect_to login_path
      redirect_to auth_path(provider: 'github')
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate!, except: [:index, :show]

  # GET /homes
  def index
    params[:search] = params[:q] if params[:q].present?
    if params[:search]
      @homes = Home.where('zip ilike :pattern or description ilike :pattern or city ilike :pattern', pattern: "%#{params[:search]}%")
    else
      @homes = Home.order(:price)
    end

    @homes = @homes.page(params[:page]).per(8)
  end

  # GET /homes/1
  def show
    @home = Home.find(params[:id])
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
    unless @home.can_this_user_edit?(current_user)
      send_them_back_with_error
    end
  end

  # POST /homes
  def create
    @home = Home.new(home_params)
    @home.created_by = current_user

    if @home.save
      redirect_to @home, notice: 'Home was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /homes/1
  def update
    @home = Home.find(params[:id])

    unless @home.can_this_user_edit?(current_user)
      redirect_to homes_path, notice: "You are not allowed to Edit this home"
    end

    if @home.update(home_params)
      redirect_to @home, notice: 'Home was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /homes/1
  def destroy
    @home = Home.find(params[:id])

    unless @home.can_this_user_destroy?(current_user)
      send_them_back_with_error
    end

    @home.destroy
    redirect_to homes_url, notice: 'Home was successfully destroyed.'
  end

  def favorite
    # unless logged_in?
      # redirect_to login_path
    # end
    home = Home.find(params[:id])
    Favorite.create(home: home, user: current_user)
    Rails.logger.debug "FAVORITING"
  end

  def unfavorite
    home = Home.find(params[:id])
    favorite = Favorite.find_by(home: home, user: current_user)
    respond_to do |format|
      if favorite.destroy
        format.json { head :ok }
      else
        format.json { head :fail , message: login_url}
      end
    end
    Rails.logger.debug "UNFAVORITING"
  end

  private

  def send_them_back_with_error
    redirect_to homes_path, notice: "You are not allowed to Edit this home"
  end

  # Only allow a trusted parameter "white list" through.
  def home_params
    params.require(:home).permit(:address, :city, :state, :zip, :bedrooms, :baths, :square_feet, :price, :description, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout false
  def landing
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      # Send the email notifying the user!
      NotificationsMailer.signup(@user).deliver_later
      # byebug
      redirect_to request.referer
    else
      redirect_to auth_path(provider: 'github')
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to homes_path
  end

  # Show the failure page
  def failure
  # TODO, create failure.html.erb
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to auth_path(provider: 'github')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def home_age_class(date)
    if date < 30.days.ago
      return "old-home"
    elsif date >= 2.days.ago
      return "new-home"
    else
      return "standard-home"
    end
  end

  def heart_class(home, user)
    # Does a favorite exist for THIS home and THIS user
    favorite = Favorite.find_by(home: home, user: user)

    if favorite
      "glyphicon-heart"
    else
      "glyphicon-heart-empty"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @home.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h4>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# address %>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>


  <%# city %>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>


  <%# state %>
  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>


  <%# zip %>
  <div class="form-group">
    <%= f.label :zip, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zip, class: "form-control" %>
    </div>
  </div>


  <%# bedrooms %>
  <div class="form-group">
    <%= f.label :bedrooms, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :bedrooms, class: "form-control" %>
    </div>
  </div>


  <%# baths %>
  <div class="form-group">
    <%= f.label :baths, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :baths, class: "form-control" %>
    </div>
  </div>


  <%# square_feet %>
  <div class="form-group">
    <%= f.label :square_feet, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :square_feet, class: "form-control" %>
    </div>
  </div>


  <%# price %>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :price, class: "form-control" %>
    </div>
  </div>


  <%# description %>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <%# image_data %>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%# upload button %>
    <%= f.hidden_field :image, value: @home.cached_image_data %>
    <%= f.file_field :image %>
    </div>
  </div>


  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end -%>

app/views/homes/_home.html.erb
<!-- Old original code -->

<!-- <li class="list-group-item">
  <div class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="<%= home.image_url(:small) %>" height="110" width="110">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= home.description %></h4>

      <div class="btn-group pull-right" role="group">
        <%= link_to home do %>
          <button type="button" class="btn-group btn-default btn-xs">View <span class="glyphicon glyphicon-home" aria-hidden="true"></span></button>
        <% end %>
        <% if logged_in? %>
          <%= link_to edit_home_path(home) do %>
            <button type="button" class="btn-group btn-default btn-xs">Edit</button>
          <% end %>
        <% end %>
        <% if logged_in? %>
          <%= link_to home, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <button type="button" class="btn-group btn-default btn-xs">Delete <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
          <% end %>
        <% end %>
      </div>

        <h5><%= home.city %>, <%= home.state %>  <%= home.zip %></h5>
        <h5>| <%= home.bedrooms %> Beds |  | <%= home.baths %> Baths |</h5>

      <ul>
        <li>Price:  <%= number_to_currency(home.price, precision: 0) %></li>

        <li>
          <div class="btn-group pull-right " role="group">
            <span data-home-id="<%= home.id %>" class="heart-art glyphicon <%= heart_class(home, current_user) %>" aria-hidden="true"></span> this home
          </div>
        </li>
      </ul>
      <ul>
        <li class="<%= home_age_class(home.created_at) %>">
          posted <%= distance_of_time_in_words_to_now(home.created_at) %> ago
        </li>

        <%= link_to home do %>
          <button type="button" class="btn-group btn-default btn-xs">View <span class="glyphicon glyphicon-home" aria-hidden="true"></span></button>
        <% end %>
        <% if logged_in? %>
          <%= link_to edit_home_path(home) do %>
            <button type="button" class="btn-group btn-default btn-xs">Edit</button>
          <% end %>
        <% end %>
        <% if logged_in? %>
          <%= link_to home, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <button type="button" class="btn-group btn-default btn-xs">Delete <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
          <% end %>
        <% end %>

      </ul>
    </div>
  </div>
</li> -->

<!-- After bootsnip element -->

<div class="col-lg-3">
   <div class="panel">
      <div class="panel-heading" style="background-color:#666;color:#fff;">
        <strong><%= home.city %>, <%= home.state %>  <%= home.zip %></strong>
      </div>
      <div class="panel-body" style="background-color:#666;color:#fff; box-shadow:0 -12px 13px green inset;">

      <%= link_to home do %>
        <div class="boximg">
         <img src="<%= home.image_url(:medium) %>" class="img-responsive">
         <span class="label label-danger date"><%= home.square_feet %> sq. feet</span>
         <span class="likebut glyphicon glyphicon-tag"></span>
        </div>
      <% end %>

      <br>
      <p class="pull-left">
        | <%= home.bedrooms %> Beds |  | <%= home.baths %> Baths |  <br>
        <%= number_to_currency(home.price, precision: 0) %>         <br>
        posted <%= distance_of_time_in_words_to_now(home.created_at) %> ago
      </p>

      <!-- Posted time ago with color red or default class -->
      <!-- <p class="<%= home_age_class(home.created_at) %>">
          posted <%= distance_of_time_in_words_to_now(home.created_at) %> ago
      </p> -->

      <!-- <span class="badge pull-right" style="background-color:teal"> -->
      <!-- </span> -->

      <div class="pull-right" role="group">
        <span data-home-id="<%= home.id %>" class="heart-art glyphicon <%= heart_class(home, current_user) %>" aria-hidden="true"></span>
      </div>


      <div class="btn-group pull-right" role="group">
        <%= link_to home do %>
          <button type="button" class="btn-group btn-default btn-xs">View <span class="glyphicon glyphicon-home" aria-hidden="true"></span></button>
        <% end %>
        <% if logged_in? %>
          <%= link_to edit_home_path(home) do %>
            <button type="button" class="btn-group btn-default btn-xs">Edit</button>
          <% end %>
        <% end %>
        <% if logged_in? %>
          <%= link_to home, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <button type="button" class="btn-group btn-default btn-xs">Delete <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
          <% end %>
        <% end %>
      </div>
    </div>
   </div>
</div>

app/views/homes/_nohomes.html.erb
<div class="jumbotron">
  <h1>No Homes Found!</h1>
  <p>search again</p>
</div>

app/views/homes/edit.html.erb
<div class="page-header">
  <%= link_to homes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @home, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>| Edit <span class="glyphicon glyphicon-home" aria-hidden="true"></span> |</h1>
</div>

<%= render 'form' %>

app/views/homes/index.html.erb
<div class="page-header">
  <%= link_to new_home_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Home
  <% end %>
  <h1><span class="posts">Tiny Estates</span></h1>
</div>

<div class="text-center">
  <%= paginate @homes %>
</div>

<ul class="homes-list-group">
  <%= render @homes %>
</ul>

<!-- Used to drop paginator down below bootsnip -->
<div class="clearfix">
</div>

<div class="text-center">
  <%= paginate @homes %>
</div>

app/views/homes/index.js.erb
console.log('This is from the server, NIIIICE. there are <%= @homes.size %> homes matched')

<% if @homes.any? %>
  $('.homes-list-group').html('<%= j(render @homes) %>')
<% else %>
  $('.homes-list-group').html('<%= j(render 'nohomes' ) %>')
<% end %>

app/views/homes/new.html.erb
<div class="page-header">
  <%= link_to homes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>| New home |</h1>
</div>

<%= render 'form' %>

app/views/homes/show.html.erb
<div class="page-header">
  <%= link_to homes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <% if logged_in? %>
    <%= link_to edit_home_path(@home), class: 'btn btn-info' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
  <% end %>
  <h1>
    <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Address:
    <%= @home.address %>
  </h1>
</div>

<!-- Columns are always 50% wide, on mobile and desktop -->
<div class="row">
  <div class="col-md-6 col-sm-12">
    <%= image_tag(@home.image_url(:medium)) %>

  </div>
  <div class="col-md-6 col-sm-12">
    <dl class="dl-horizontal">
      <h2><%= @home.city %>, <%= @home.state %>  <%= @home.zip %></h2>
      <h4>| <%= @home.bedrooms %> beds | | <%= @home.baths %> baths | | <%= @home.square_feet %> sq. feet |</h4>
      <h5><span class="glyphicon glyphicon-home" aria-hidden="true"></span></h5>
      <div class="well well-sm"><h3>FOR SALE:  <%= number_to_currency(@home.price, precision: 0) %></h3></div>
      <div class="well well-sm">Description: <h4><%= @home.description %></h4></div>
  </div>
</div>

<div class="map"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.module_parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <!-- GMap3 gem dependencies -->
  <!-- <link href="../styles.css" rel="stylesheet"> -->
  <script src="http://maps.google.com/maps/api/js?key=AIzaSyCxrRjzlP0FYye5A0jZSpMrBLq_5vEC2fA"></script>
  <script src="https://cdn.jsdelivr.net/gmap3/7.2.0/gmap3.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>



  <!-- Favicon -->
  <%= favicon_link_tag 'home.ico' %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "/", class: "navbar-brand" do %>
          Homepage
        <% end %>
      </div>

      <div id="navbar" class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
          <%= form_tag(homes_path, :method => "get", id: "search-form", class: "navbar-form navbar-right form-inline") do %>
            <li class="active">
              <div class="form-group">
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search...", style: 'width: 400px' %>
              </div>
                <% end %>
            </li>
        </ul>

        <% if logged_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">| Logged in: <%= current_user.name %> |</p>
            </li>
            <li>
              <p class="navbar-text"><%= link_to "| Logout |", logout_path %></p>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text"><%= link_to "| Log in |", auth_path(provider: "GitHub") %></p>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.module_parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>

  <!-- <script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>  -->
  <!-- only if you need custom infoboxes -->


  <!-- Favicon -->
  <%= favicon_link_tag 'home.ico' %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <div class="jumbotron landing-jumbotron">
    <div class="container">
      <h1><span class="posts">Tiny Estates</span></h1>
      <p>Your Homestead escape from the conventional high priced mortgage <span class="glyphicon glyphicon-home" aria-hidden="true"></span></p>

      <%= form_tag homes_path , method: :get do -%>
        <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "Search for your dream home..." %>
        <br>
        <%= submit_tag "Submit", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <%= link_to "| Sign in with GitHub |", auth_path(provider: "github"), class: "btn btn-default" %>
    <!-- <%= link_to "| sign in with Facebook |", auth_path(provider: "facebook"), class: "btn btn-default" %> -->
    <%= link_to "| View Tiny Homes |", homes_path, class: "btn btn-success" %>
  </div>
</body>
</html>

app/views/pages/session/new.html.erb
<%= link_to 'Login with Github', auth_path(provider: 'github') %>